name: develop - Build Android debug app

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install app dependencies
        run: npm install

      - name: Fixing Android Build Tool Issue
        run: |
            cd $ANDROID_HOME/build-tools/33.0.0
            mv d8 dx
            cd lib
            mv d8.jar dx.jar
            
      - name: write temp file for version/ build number
        run: |
#          rm ${{ github.workspace }}/hooks/buildnumber.txt
          touch ${{ github.workspace }}/hooks/buildnumber.txt
          printf -v BUILDNUMBER "%04ddev" ${{github.run_number}}
          echo $BUILDNUMBER >> ${{ github.workspace }}/hooks/buildnumber.txt
          echo "cat ../buildnumber.txt"
          cat ${{ github.workspace }}/hooks/buildnumber.txt
          VERSIONNUMBER=`cat ${{ github.workspace }}/hooks/versionnumber.txt`
          echo "cat ../hooks/versionnumber.txt"
          cat ${{ github.workspace }}/hooks/hooks/versionnumber.txt
          echo "CURRENT_VERSIONNUMBER=$VERSIONNUMBER" >> $GITHUB_ENV
          echo "CURRENT_BUILDNUMBER=$BUILDNUMBER" >> $GITHUB_ENV

      - name: Add Android platform
        run : |
          cordova platform add android

      - name: Build Android Dev APK
        run: |
          cordova build android
        
      - name: Upload dev APK
        uses: actions/upload-artifact@v3
        with:
          name: 3DprinterStatus_${{ env.CURRENT_VERSIONNUMBER }}.${{ env.CURRENT_BUILDNUMBER }}.apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
#      - name: Build & Publish Debug APK
#        uses: kyze8439690/action-release-releaseapk@master
#        env:
#              GITHUB_TOKEN: ${{ secrets.TOKEN }}
#              APP_FOLDER: platforms/android/app/build/outputs/apk/debug
      # - name: Releasing using Hub
      #   uses: r0user/release-apk@main
      #   env:
      #    GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #    APP_FOLDER: platforms/android/app/build/outputs/apk/debug
